// <auto-generated source="dd-index.js (DrunkDeer official web driver)" />
//
// Verified layout data for all 19 DrunkDeer keyboard models, extracted from the
// official web driver bundle (dd-index.js). Each model's m_kbdLayout array is
// reproduced verbatim — exactly 126 entries per layout, with empty slots as "".
//
// Cross-checked against a real A75 Ultra Profile1.json export. Type-code / type-byte
// triples come from the firmware identification packets in the same JS bundle.
//
// USB PIDs are only filled in where confidence is high (A75 Pro, A75 Ultra).
// Other PIDs in DrunkDeerKeyboards remain empty until telemetry confirms a
// mapping — see [[hardware-pid-quirks]]: an A75 Pro was observed enumerating
// as 0x2383, which we previously assumed was G65-only, so PID is not a
// reliable identifier on its own.

#nullable enable

namespace Driver;

public sealed record KeyboardModel
{
    public required string ProfilePrefix { get; init; }
    public required string DisplayName { get; init; }
    public required int TypeCode { get; init; }
    public required (byte B4, byte B5, byte B6) TypeBytes { get; init; }
    // USB Product IDs that resolve to this model. A model can expose more than
    // one PID (e.g. the A75 Pro has both 0x2391 and 0x2a08 — second interface).
    // Empty when the PID-to-model mapping isn't confirmed yet.
    public IReadOnlyList<int> Pids { get; init; } = [];
    public required IReadOnlyList<string> KeyNames { get; init; }

    public int NamedSlotCount =>
        KeyNames.Count(n => !string.IsNullOrEmpty(n));
}

public static class KeyboardModels
{
    // ---- Layouts (126 entries each, verbatim from dd-index.js) ----

    /// <summary>A75 Pro — 126-key layout from ddeerA75ProProfile.</summary>
    public static readonly IReadOnlyList<string> A75ProLayout =
    [
        "ESC", "", "F1", "F2", "F3", "F4", "F5", "F6", 
        "F7", "F8", "F9", "F10", "F11", "F12", "KP7", "KP8", 
        "KP9", "", "", "", "", "SWUNG", "1", "2", 
        "3", "4", "5", "6", "7", "8", "9", "0", 
        "MINUS", "PLUS", "BACK", "KP4", "KP5", "KP6", "", "", 
        "", "", "TAB", "Q", "W", "E", "R", "T", 
        "Y", "U", "I", "O", "P", "BRKTS_L", "BRKTS_R", "SLASH_K29", 
        "KP1", "KP2", "KP3", "", "", "", "", "CAPS", 
        "A", "S", "D", "F", "G", "H", "J", "K", 
        "L", "COLON", "QOTATN", "", "RETURN", "", "KP0", "KP_DEL", 
        "", "", "", "", "SHF_L", "EUR_K45", "Z", "X", 
        "C", "V", "B", "N", "M", "COMMA", "PERIOD", "VIRGUE", 
        "", "SHF_R", "ARR_UP", "", "NUMS", "", "", "", 
        "", "CTRL_L", "WIN_L", "ALT_L", "", "", "", "SPACE", 
        "", "", "", "ALT_R", "FN1", "APP", "ARR_L", "ARR_DW", 
        "ARR_R", "CTRL_R", "", "", "", ""
    ];

    /// <summary>A75 — 126-key layout from ddeerA75Profile.</summary>
    public static readonly IReadOnlyList<string> A75Layout =
    [
        "ESC", "", "F1", "F2", "F3", "F4", "F5", "F6", 
        "F7", "F8", "F9", "F10", "F11", "F12", "KP7", "KP8", 
        "KP9", "", "", "", "", "SWUNG", "1", "2", 
        "3", "4", "5", "6", "7", "8", "9", "0", 
        "MINUS", "PLUS", "BACK", "KP4", "KP5", "KP6", "", "", 
        "", "", "TAB", "Q", "W", "E", "R", "T", 
        "Y", "U", "I", "O", "P", "BRKTS_L", "BRKTS_R", "SLASH_K29", 
        "KP1", "KP2", "KP3", "", "", "", "", "CAPS", 
        "A", "S", "D", "F", "G", "H", "J", "K", 
        "L", "COLON", "QOTATN", "", "RETURN", "", "KP0", "KP_DEL", 
        "", "", "", "", "SHF_L", "EUR_K45", "Z", "X", 
        "C", "V", "B", "N", "M", "COMMA", "PERIOD", "VIRGUE", 
        "", "SHF_R", "ARR_UP", "", "NUMS", "", "", "", 
        "", "CTRL_L", "WIN_L", "ALT_L", "", "", "", "SPACE", 
        "", "", "", "ALT_R", "FN1", "APP", "ARR_L", "ARR_DW", 
        "ARR_R", "CTRL_R", "", "", "", ""
    ];

    /// <summary>A75 Ultra — 126-key layout from ddeerA75UltraProfile.</summary>
    public static readonly IReadOnlyList<string> A75UltraLayout =
    [
        "ESC", "", "F1", "F2", "F3", "F4", "F5", "F6", 
        "F7", "F8", "F9", "F10", "F11", "F12", "KP7", "KP8", 
        "KP9", "", "", "", "", "SWUNG", "1", "2", 
        "3", "4", "5", "6", "7", "8", "9", "0", 
        "MINUS", "PLUS", "BACK", "KP4", "KP5", "KP6", "", "", 
        "", "", "TAB", "Q", "W", "E", "R", "T", 
        "Y", "U", "I", "O", "P", "BRKTS_L", "BRKTS_R", "SLASH_K29", 
        "KP1", "KP2", "KP3", "", "", "", "", "CAPS", 
        "A", "S", "D", "F", "G", "H", "J", "K", 
        "L", "COLON", "QOTATN", "", "RETURN", "", "KP0", "KP_DEL", 
        "", "", "", "", "SHF_L", "EUR_K45", "Z", "X", 
        "C", "V", "B", "N", "M", "COMMA", "PERIOD", "VIRGUE", 
        "", "SHF_R", "ARR_UP", "NUMS", "", "", "", "", 
        "", "CTRL_L", "WIN_L", "ALT_L", "", "", "", "SPACE", 
        "", "", "", "ALT_R", "FN1", "APP", "ARR_L", "ARR_DW", 
        "ARR_R", "CTRL_R", "", "", "", ""
    ];

    /// <summary>A75 Master — 126-key layout from ddeerA75MasterProfile.</summary>
    public static readonly IReadOnlyList<string> A75MasterLayout =
    [
        "ESC", "", "F1", "F2", "F3", "F4", "F5", "F6", 
        "F7", "F8", "F9", "F10", "F11", "F12", "KP7", "KP8", 
        "KP9", "", "", "", "", "SWUNG", "1", "2", 
        "3", "4", "5", "6", "7", "8", "9", "0", 
        "MINUS", "PLUS", "BACK", "KP4", "KP5", "KP6", "", "", 
        "", "", "TAB", "Q", "W", "E", "R", "T", 
        "Y", "U", "I", "O", "P", "BRKTS_L", "BRKTS_R", "SLASH_K29", 
        "KP1", "KP2", "KP3", "", "", "", "", "CAPS", 
        "A", "S", "D", "F", "G", "H", "J", "K", 
        "L", "COLON", "QOTATN", "", "RETURN", "", "KP0", "KP_DEL", 
        "", "", "", "", "SHF_L", "EUR_K45", "Z", "X", 
        "C", "V", "B", "N", "M", "COMMA", "PERIOD", "VIRGUE", 
        "", "SHF_R", "ARR_UP", "NUMS", "", "", "", "", 
        "", "CTRL_L", "WIN_L", "ALT_L", "", "", "", "SPACE", 
        "", "", "", "ALT_R", "FN1", "APP", "ARR_L", "ARR_DW", 
        "ARR_R", "CTRL_R", "", "", "", ""
    ];

    /// <summary>A75 UK — 126-key layout from ddeerA75UKProfile.</summary>
    public static readonly IReadOnlyList<string> A75UKLayout =
    [
        "ESC", "", "F1", "F2", "F3", "F4", "F5", "F6", 
        "F7", "F8", "F9", "F10", "F11", "F12", "KP7", "KP8", 
        "KP9", "", "", "", "", "SWUNG", "1", "2", 
        "3", "4", "5", "6", "7", "8", "9", "0", 
        "MINUS", "PLUS", "BACK", "KP4", "KP5", "KP6", "", "", 
        "", "", "TAB", "Q", "W", "E", "R", "T", 
        "Y", "U", "I", "O", "P", "BRKTS_L", "BRKTS_R", "SLASH_K29", 
        "KP1", "KP2", "KP3", "", "", "", "", "CAPS", 
        "A", "S", "D", "F", "G", "H", "J", "K", 
        "L", "COLON", "QOTATN", "EUR_K42", "RETURN", "", "KP0", "KP_DEL", 
        "", "", "", "", "SHF_L", "EUR_K45", "Z", "X", 
        "C", "V", "B", "N", "M", "COMMA", "PERIOD", "VIRGUE", 
        "", "SHF_R", "ARR_UP", "", "NUMS", "", "", "", 
        "", "CTRL_L", "WIN_L", "ALT_L", "", "", "", "SPACE", 
        "", "", "", "ALT_R", "FN1", "APP", "ARR_L", "ARR_DW", 
        "ARR_R", "CTRL_R", "", "", "", ""
    ];

    /// <summary>A75 FR — 126-key layout from ddeerA75FRProfile.</summary>
    public static readonly IReadOnlyList<string> A75FRLayout =
    [
        "ESC", "", "F1", "F2", "F3", "F4", "F5", "F6", 
        "F7", "F8", "F9", "F10", "F11", "F12", "KP7", "KP8", 
        "KP9", "", "", "", "", "SWUNG", "1", "2", 
        "3", "4", "5", "6", "7", "8", "9", "0", 
        "MINUS", "PLUS", "BACK", "KP4", "KP5", "KP6", "", "", 
        "", "", "TAB", "Q", "W", "E", "R", "T", 
        "Y", "U", "I", "O", "P", "BRKTS_L", "BRKTS_R", "SLASH_K29", 
        "KP1", "KP2", "KP3", "", "", "", "", "CAPS", 
        "A", "S", "D", "F", "G", "H", "J", "K", 
        "L", "COLON", "QOTATN", "EUR_K42", "RETURN", "", "KP0", "KP_DEL", 
        "", "", "", "", "SHF_L", "EUR_K45", "Z", "X", 
        "C", "V", "B", "N", "M", "COMMA", "PERIOD", "VIRGUE", 
        "", "SHF_R", "ARR_UP", "", "NUMS", "", "", "", 
        "", "CTRL_L", "WIN_L", "ALT_L", "", "", "", "SPACE", 
        "", "", "", "ALT_R", "FN1", "APP", "ARR_L", "ARR_DW", 
        "ARR_R", "CTRL_R", "", "", "", ""
    ];

    /// <summary>A75 DE — 126-key layout from ddeerA75DEProfile.</summary>
    public static readonly IReadOnlyList<string> A75DELayout =
    [
        "ESC", "", "F1", "F2", "F3", "F4", "F5", "F6", 
        "F7", "F8", "F9", "F10", "F11", "F12", "KP7", "KP8", 
        "KP9", "", "", "", "", "SWUNG", "1", "2", 
        "3", "4", "5", "6", "7", "8", "9", "0", 
        "MINUS", "PLUS", "BACK", "KP4", "KP5", "KP6", "", "", 
        "", "", "TAB", "Q", "W", "E", "R", "T", 
        "Y", "U", "I", "O", "P", "BRKTS_L", "BRKTS_R", "SLASH_K29", 
        "KP1", "KP2", "KP3", "", "", "", "", "CAPS", 
        "A", "S", "D", "F", "G", "H", "J", "K", 
        "L", "COLON", "QOTATN", "EUR_K42", "RETURN", "", "KP0", "KP_DEL", 
        "", "", "", "", "SHF_L", "EUR_K45", "Z", "X", 
        "C", "V", "B", "N", "M", "COMMA", "PERIOD", "VIRGUE", 
        "", "SHF_R", "ARR_UP", "", "NUMS", "", "", "", 
        "", "CTRL_L", "WIN_L", "ALT_L", "", "", "", "SPACE", 
        "", "", "", "ALT_R", "FN1", "APP", "ARR_L", "ARR_DW", 
        "ARR_R", "CTRL_R", "", "", "", ""
    ];

    /// <summary>G75 — 126-key layout from ddeerG75Profile.</summary>
    public static readonly IReadOnlyList<string> G75Layout =
    [
        "ESC", "F1", "F2", "F3", "F4", "F5", "F6", "F7", 
        "F8", "F9", "F10", "F11", "F12", "PRINT", "INSERT", "DELETE", 
        "", "", "", "", "", "SWUNG", "1", "2", 
        "3", "4", "5", "6", "7", "8", "9", "0", 
        "MINUS", "PLUS", "BACK", "", "HOME", "", "", "", 
        "", "", "TAB", "Q", "W", "E", "R", "T", 
        "Y", "U", "I", "O", "P", "BRKTS_L", "BRKTS_R", "SLASH_K29", 
        "", "PAGEUP", "", "", "", "", "", "CAPS", 
        "A", "S", "D", "F", "G", "H", "J", "K", 
        "L", "COLON", "QOTATN", "EUR_K42", "RETURN", "", "PAGEDW", "", 
        "", "", "", "", "SHF_L", "EUR_K45", "Z", "X", 
        "C", "V", "B", "N", "M", "COMMA", "PERIOD", "VIRGUE", 
        "SHF_R", "ARR_UP", "", "END", "", "", "", "", 
        "", "CTRL_L", "WIN_L", "ALT_L", "", "", "", "SPACE", 
        "", "", "ALT_R", "FN1", "", "FN2", "ARR_L", "ARR_DW", 
        "ARR_R", "", "", "", "", ""
    ];

    /// <summary>G75 JP — 126-key layout from ddeerG75JPProfile.</summary>
    public static readonly IReadOnlyList<string> G75JPLayout =
    [
        "ESC", "F1", "F2", "F3", "F4", "F5", "F6", "F7", 
        "F8", "F9", "F10", "F11", "F12", "PRINT", "INSERT", "DELETE", 
        "", "", "", "", "", "SWUNG", "1", "2", 
        "3", "4", "5", "6", "7", "8", "9", "0", 
        "MINUS", "PLUS", "JAP_3_K14", "BACK", "HOME", "", "", "", 
        "", "", "TAB", "Q", "W", "E", "R", "T", 
        "Y", "U", "I", "O", "P", "BRKTS_L", "BRKTS_R", "", 
        "", "PAGEUP", "", "", "", "", "", "CAPS", 
        "A", "S", "D", "F", "G", "H", "J", "K", 
        "L", "COLON", "QOTATN", "EUR_K42", "", "RETURN", "PAGEDW", "", 
        "", "", "", "", "SHF_L", "", "Z", "X", 
        "C", "V", "B", "N", "M", "COMMA", "PERIOD", "VIRGUE", 
        "JAP_1_K56", "SHF_R", "ARR_UP", "END", "", "", "", "", 
        "", "CTRL_L", "WIN_L", "ALT_L", "", "", "", "SPACE", 
        "", "", "ALT_R", "FN1", "", "CTRL_R", "ARR_L", "ARR_DW", 
        "ARR_R", "", "", "", "", ""
    ];

    /// <summary>G65 — 126-key layout from ddeerG65Profile.</summary>
    public static readonly IReadOnlyList<string> G65Layout =
    [
        "", "", "", "", "", "", "", "", 
        "", "", "", "", "", "", "", "", 
        "", "", "", "", "", "ESC", "1", "2", 
        "3", "4", "5", "6", "7", "8", "9", "0", 
        "MINUS", "PLUS", "BACK", "DELETE", "", "", "", "", 
        "", "", "TAB", "Q", "W", "E", "R", "T", 
        "Y", "U", "I", "O", "P", "BRKTS_L", "BRKTS_R", "SLASH_K29", 
        "END", "", "", "", "", "", "", "CAPS", 
        "A", "S", "D", "F", "G", "H", "J", "K", 
        "L", "COLON", "QOTATN", "EUR_K42", "RETURN", "PAGEUP", "", "", 
        "", "", "", "", "SHF_L", "EUR_K45", "Z", "X", 
        "C", "V", "B", "N", "M", "COMMA", "PERIOD", "VIRGUE", 
        "SHF_R", "ARR_UP", "PAGEDW", "", "", "", "", "", 
        "", "CTRL_L", "WIN_L", "ALT_L", "", "", "", "SPACE", 
        "", "", "ALT_R", "FN1", "FN2", "ARR_L", "ARR_DW", "ARR_R", 
        "", "", "", "", "", ""
    ];

    /// <summary>G65 Lite — 126-key layout from ddeerG65liteProfile.</summary>
    public static readonly IReadOnlyList<string> G65LiteLayout =
    [
        "", "", "", "", "", "", "", "", 
        "", "", "", "", "", "", "", "", 
        "", "", "", "", "", "ESC", "1", "2", 
        "3", "4", "5", "6", "7", "8", "9", "0", 
        "MINUS", "PLUS", "BACK", "DELETE", "", "", "", "", 
        "", "", "TAB", "Q", "W", "E", "R", "T", 
        "Y", "U", "I", "O", "P", "BRKTS_L", "BRKTS_R", "SLASH_K29", 
        "END", "", "", "", "", "", "", "CAPS", 
        "A", "S", "D", "F", "G", "H", "J", "K", 
        "L", "COLON", "QOTATN", "EUR_K42", "RETURN", "PAGEUP", "", "", 
        "", "", "", "", "SHF_L", "EUR_K45", "Z", "X", 
        "C", "V", "B", "N", "M", "COMMA", "PERIOD", "VIRGUE", 
        "SHF_R", "ARR_UP", "PAGEDW", "", "", "", "", "", 
        "", "CTRL_L", "WIN_L", "ALT_L", "", "", "", "SPACE", 
        "", "", "ALT_R", "FN1", "FN2", "ARR_L", "ARR_DW", "ARR_R", 
        "", "", "", "", "", ""
    ];

    /// <summary>G65 m1 — 126-key layout from ddeerG65m1Profile.</summary>
    public static readonly IReadOnlyList<string> G65m1Layout =
    [
        "", "", "", "", "", "", "", "", 
        "", "", "", "", "", "", "", "", 
        "", "", "", "", "", "ESC", "1", "2", 
        "3", "4", "5", "6", "7", "8", "9", "0", 
        "MINUS", "PLUS", "BACK", "DELETE", "", "", "", "", 
        "", "", "TAB", "Q", "W", "E", "R", "T", 
        "Y", "U", "I", "O", "P", "BRKTS_L", "BRKTS_R", "SLASH_K29", 
        "END", "", "", "", "", "", "", "CAPS", 
        "A", "S", "D", "F", "G", "H", "J", "K", 
        "L", "COLON", "QOTATN", "EUR_K42", "RETURN", "PAGEUP", "", "", 
        "", "", "", "", "SHF_L", "EUR_K45", "Z", "X", 
        "C", "V", "B", "N", "M", "COMMA", "PERIOD", "VIRGUE", 
        "SHF_R", "ARR_UP", "PAGEDW", "", "", "", "", "", 
        "", "CTRL_L", "WIN_L", "ALT_L", "", "", "", "SPACE", 
        "", "", "ALT_R", "FN1", "FN2", "ARR_L", "ARR_DW", "ARR_R", 
        "", "", "", "", "", ""
    ];

    /// <summary>G65 m2 — 126-key layout from ddeerG65m2Profile.</summary>
    public static readonly IReadOnlyList<string> G65m2Layout =
    [
        "", "", "", "", "", "", "", "", 
        "", "", "", "", "", "", "", "", 
        "", "", "", "", "", "ESC", "1", "2", 
        "3", "4", "5", "6", "7", "8", "9", "0", 
        "MINUS", "PLUS", "BACK", "DELETE", "", "", "", "", 
        "", "", "TAB", "Q", "W", "E", "R", "T", 
        "Y", "U", "I", "O", "P", "BRKTS_L", "BRKTS_R", "SLASH_K29", 
        "END", "", "", "", "", "", "", "CAPS", 
        "A", "S", "D", "F", "G", "H", "J", "K", 
        "L", "COLON", "QOTATN", "EUR_K42", "RETURN", "PAGEUP", "", "", 
        "", "", "", "", "SHF_L", "EUR_K45", "Z", "X", 
        "C", "V", "B", "N", "M", "COMMA", "PERIOD", "VIRGUE", 
        "SHF_R", "ARR_UP", "PAGEDW", "", "", "", "", "", 
        "", "CTRL_L", "WIN_L", "ALT_L", "", "", "", "SPACE", 
        "", "", "ALT_R", "FN1", "FN2", "ARR_L", "ARR_DW", "ARR_R", 
        "", "", "", "", "", ""
    ];

    /// <summary>G65 m3 — 126-key layout from ddeerG65m3Profile.</summary>
    public static readonly IReadOnlyList<string> G65m3Layout =
    [
        "", "", "", "", "", "", "", "", 
        "", "", "", "", "", "", "", "", 
        "", "", "", "", "", "ESC", "1", "2", 
        "3", "4", "5", "6", "7", "8", "9", "0", 
        "MINUS", "PLUS", "BACK", "DELETE", "", "", "", "", 
        "", "", "TAB", "Q", "W", "E", "R", "T", 
        "Y", "U", "I", "O", "P", "BRKTS_L", "BRKTS_R", "SLASH_K29", 
        "END", "", "", "", "", "", "", "CAPS", 
        "A", "S", "D", "F", "G", "H", "J", "K", 
        "L", "COLON", "QOTATN", "EUR_K42", "RETURN", "PAGEUP", "", "", 
        "", "", "", "", "SHF_L", "EUR_K45", "Z", "X", 
        "C", "V", "B", "N", "M", "COMMA", "PERIOD", "VIRGUE", 
        "SHF_R", "ARR_UP", "PAGEDW", "", "", "", "", "", 
        "", "CTRL_L", "WIN_L", "ALT_L", "", "", "", "SPACE", 
        "", "", "ALT_R", "FN1", "FN2", "ARR_L", "ARR_DW", "ARR_R", 
        "", "", "", "", "", ""
    ];

    /// <summary>G60 — 126-key layout from ddeerG60Profile.</summary>
    public static readonly IReadOnlyList<string> G60Layout =
    [
        "", "", "", "", "", "", "", "", 
        "", "", "", "", "", "", "", "", 
        "", "", "", "", "", "ESC", "1", "2", 
        "3", "4", "5", "6", "7", "8", "9", "0", 
        "MINUS", "PLUS", "BACK", "", "", "", "", "", 
        "", "", "TAB", "Q", "W", "E", "R", "T", 
        "Y", "U", "I", "O", "P", "BRKTS_L", "BRKTS_R", "SLASH_K29", 
        "", "", "", "", "", "", "", "CAPS", 
        "A", "S", "D", "F", "G", "H", "J", "K", 
        "L", "COLON", "QOTATN", "EUR_K42", "RETURN", "", "", "", 
        "", "", "", "", "SHF_L", "EUR_K45", "Z", "X", 
        "C", "V", "B", "N", "M", "COMMA", "PERIOD", "VIRGUE", 
        "", "SHF_R", "", "", "", "", "", "", 
        "", "CTRL_L", "WIN_L", "ALT_L", "", "", "", "SPACE", 
        "", "", "", "ALT_R", "FN1", "FN2", "CTRL_R", "", 
        "", "", "", "", "", ""
    ];

    /// <summary>G60 m1 — 126-key layout from ddeerG60m1Profile.</summary>
    public static readonly IReadOnlyList<string> G60m1Layout =
    [
        "", "", "", "", "", "", "", "", 
        "", "", "", "", "", "", "", "", 
        "", "", "", "", "", "ESC", "1", "2", 
        "3", "4", "5", "6", "7", "8", "9", "0", 
        "MINUS", "PLUS", "BACK", "", "", "", "", "", 
        "", "", "TAB", "Q", "W", "E", "R", "T", 
        "Y", "U", "I", "O", "P", "BRKTS_L", "BRKTS_R", "SLASH_K29", 
        "", "", "", "", "", "", "", "CAPS", 
        "A", "S", "D", "F", "G", "H", "J", "K", 
        "L", "COLON", "QOTATN", "EUR_K42", "RETURN", "", "", "", 
        "", "", "", "", "SHF_L", "EUR_K45", "Z", "X", 
        "C", "V", "B", "N", "M", "COMMA", "PERIOD", "VIRGUE", 
        "", "SHF_R", "", "", "", "", "", "", 
        "", "CTRL_L", "WIN_L", "ALT_L", "", "", "", "SPACE", 
        "", "", "", "ALT_R", "FN1", "FN2", "CTRL_R", "", 
        "", "", "", "", "", ""
    ];

    /// <summary>G60 m2 — 126-key layout from ddeerG60m2Profile.</summary>
    public static readonly IReadOnlyList<string> G60m2Layout =
    [
        "", "", "", "", "", "", "", "", 
        "", "", "", "", "", "", "", "", 
        "", "", "", "", "", "ESC", "1", "2", 
        "3", "4", "5", "6", "7", "8", "9", "0", 
        "MINUS", "PLUS", "BACK", "", "", "", "", "", 
        "", "", "TAB", "Q", "W", "E", "R", "T", 
        "Y", "U", "I", "O", "P", "BRKTS_L", "BRKTS_R", "SLASH_K29", 
        "", "", "", "", "", "", "", "CAPS", 
        "A", "S", "D", "F", "G", "H", "J", "K", 
        "L", "COLON", "QOTATN", "EUR_K42", "RETURN", "", "", "", 
        "", "", "", "", "SHF_L", "EUR_K45", "Z", "X", 
        "C", "V", "B", "N", "M", "COMMA", "PERIOD", "VIRGUE", 
        "", "SHF_R", "", "", "", "", "", "", 
        "", "CTRL_L", "WIN_L", "ALT_L", "", "", "", "SPACE", 
        "", "", "", "ALT_R", "FN1", "FN2", "CTRL_R", "", 
        "", "", "", "", "", ""
    ];

    /// <summary>G60 m3 — 126-key layout from ddeerG60m3Profile.</summary>
    public static readonly IReadOnlyList<string> G60m3Layout =
    [
        "", "", "", "", "", "", "", "", 
        "", "", "", "", "", "", "", "", 
        "", "", "", "", "", "ESC", "1", "2", 
        "3", "4", "5", "6", "7", "8", "9", "0", 
        "MINUS", "PLUS", "BACK", "", "", "", "", "", 
        "", "", "TAB", "Q", "W", "E", "R", "T", 
        "Y", "U", "I", "O", "P", "BRKTS_L", "BRKTS_R", "SLASH_K29", 
        "", "", "", "", "", "", "", "CAPS", 
        "A", "S", "D", "F", "G", "H", "J", "K", 
        "L", "COLON", "QOTATN", "EUR_K42", "RETURN", "", "", "", 
        "", "", "", "", "SHF_L", "EUR_K45", "Z", "X", 
        "C", "V", "B", "N", "M", "COMMA", "PERIOD", "VIRGUE", 
        "", "SHF_R", "", "", "", "", "", "", 
        "", "CTRL_L", "WIN_L", "ALT_L", "", "", "", "SPACE", 
        "", "", "", "ALT_R", "FN1", "FN2", "CTRL_R", "", 
        "", "", "", "", "", ""
    ];

    /// <summary>X60 — 126-key layout from ddeerX60Profile.</summary>
    public static readonly IReadOnlyList<string> X60Layout =
    [
        "ESC", "", "F1", "F2", "F3", "F4", "F5", "F6", 
        "F7", "F8", "F9", "F10", "F11", "F12", "KP7", "KP8", 
        "KP9", "", "", "", "", "SWUNG", "1", "2", 
        "3", "4", "5", "6", "7", "8", "9", "0", 
        "MINUS", "PLUS", "BACK", "KP4", "KP5", "KP6", "", "", 
        "", "", "TAB", "Q", "W", "E", "R", "T", 
        "Y", "U", "I", "O", "P", "BRKTS_L", "BRKTS_R", "SLASH_K29", 
        "KP1", "KP2", "KP3", "", "", "", "", "CAPS", 
        "A", "S", "D", "F", "G", "H", "J", "K", 
        "L", "COLON", "QOTATN", "", "RETURN", "", "KP0", "KP_DEL", 
        "", "", "", "", "SHF_L", "EUR_K45", "Z", "X", 
        "C", "V", "B", "N", "M", "COMMA", "PERIOD", "VIRGUE", 
        "", "SHF_R", "ARR_UP", "NUMS", "", "", "", "", 
        "", "CTRL_L", "WIN_L", "ALT_L", "", "", "", "SPACE", 
        "", "", "", "ALT_R", "FN1", "APP", "ARR_L", "ARR_DW", 
        "ARR_R", "CTRL_R", "", "", "", ""
    ];

    // ---- Model records ----

    public static readonly KeyboardModel A75ProModel = new()
    {
        ProfilePrefix = "ddeerA75ProProfile",
        DisplayName = "A75 Pro",
        TypeCode = 750,
        TypeBytes = (11, 4, 3),
        Pids = [0x2391, 0x2a08],
        KeyNames = A75ProLayout,
    };

    public static readonly KeyboardModel A75Model = new()
    {
        ProfilePrefix = "ddeerA75Profile",
        DisplayName = "A75",
        TypeCode = 75,
        TypeBytes = (11, 4, 1),
        KeyNames =A75Layout,
    };

    public static readonly KeyboardModel A75UltraModel = new()
    {
        ProfilePrefix = "ddeerA75UltraProfile",
        DisplayName = "A75 Ultra",
        TypeCode = 756,
        TypeBytes = (11, 4, 4),
        Pids = [0x2387],
        KeyNames = A75UltraLayout,
    };

    public static readonly KeyboardModel A75MasterModel = new()
    {
        ProfilePrefix = "ddeerA75MasterProfile",
        DisplayName = "A75 Master",
        TypeCode = 757,
        TypeBytes = (11, 5, 4),
        KeyNames =A75MasterLayout,
    };

    public static readonly KeyboardModel A75UKModel = new()
    {
        ProfilePrefix = "ddeerA75UKProfile",
        DisplayName = "A75 UK",
        TypeCode = 751,
        TypeBytes = (11, 4, 2),
        KeyNames =A75UKLayout,
    };

    public static readonly KeyboardModel A75FRModel = new()
    {
        ProfilePrefix = "ddeerA75FRProfile",
        DisplayName = "A75 FR",
        TypeCode = 751,
        TypeBytes = (11, 4, 2),
        KeyNames =A75FRLayout,
    };

    public static readonly KeyboardModel A75DEModel = new()
    {
        ProfilePrefix = "ddeerA75DEProfile",
        DisplayName = "A75 DE",
        TypeCode = 751,
        TypeBytes = (11, 4, 2),
        KeyNames =A75DELayout,
    };

    public static readonly KeyboardModel G75Model = new()
    {
        ProfilePrefix = "ddeerG75Profile",
        DisplayName = "G75",
        TypeCode = 754,
        TypeBytes = (11, 4, 5),
        KeyNames =G75Layout,
    };

    public static readonly KeyboardModel G75JPModel = new()
    {
        ProfilePrefix = "ddeerG75JPProfile",
        DisplayName = "G75 JP",
        TypeCode = 755,
        TypeBytes = (11, 4, 7),
        KeyNames =G75JPLayout,
    };

    public static readonly KeyboardModel G65Model = new()
    {
        ProfilePrefix = "ddeerG65Profile",
        DisplayName = "G65",
        TypeCode = 65,
        TypeBytes = (11, 2, 1),
        // PID intentionally blank: a confirmed A75 Pro has been observed
        // enumerating as 0x2383 in the field (debug.log 2026-05-14), so the
        // earlier 0x2383→G65 assumption is at best incomplete. Let TypeCode
        // (65) be the authoritative resolver path; telemetry will tell us
        // whether real G65 units also report 0x2383 before we re-add it.
        KeyNames = G65Layout,
    };

    public static readonly KeyboardModel G65LiteModel = new()
    {
        ProfilePrefix = "ddeerG65liteProfile",
        DisplayName = "G65 Lite",
        TypeCode = 650,
        TypeBytes = (11, 2, 5),
        KeyNames =G65LiteLayout,
    };

    public static readonly KeyboardModel G65m1Model = new()
    {
        ProfilePrefix = "ddeerG65m1Profile",
        DisplayName = "G65 m1",
        TypeCode = 651,
        TypeBytes = (11, 2, 3),
        KeyNames =G65m1Layout,
    };

    public static readonly KeyboardModel G65m2Model = new()
    {
        ProfilePrefix = "ddeerG65m2Profile",
        DisplayName = "G65 m2",
        TypeCode = 652,
        TypeBytes = (11, 16, 1),
        KeyNames =G65m2Layout,
    };

    public static readonly KeyboardModel G65m3Model = new()
    {
        ProfilePrefix = "ddeerG65m3Profile",
        DisplayName = "G65 m3",
        TypeCode = 653,
        TypeBytes = (11, 18, 1),
        KeyNames =G65m3Layout,
    };

    public static readonly KeyboardModel G60Model = new()
    {
        ProfilePrefix = "ddeerG60Profile",
        DisplayName = "G60",
        TypeCode = 60,
        TypeBytes = (11, 3, 1),
        KeyNames =G60Layout,
    };

    public static readonly KeyboardModel G60m1Model = new()
    {
        ProfilePrefix = "ddeerG60m1Profile",
        DisplayName = "G60 m1",
        TypeCode = 600,
        TypeBytes = (11, 3, 3),
        KeyNames =G60m1Layout,
    };

    public static readonly KeyboardModel G60m2Model = new()
    {
        ProfilePrefix = "ddeerG60m2Profile",
        DisplayName = "G60 m2",
        TypeCode = 601,
        TypeBytes = (11, 19, 1),
        KeyNames =G60m2Layout,
    };

    public static readonly KeyboardModel G60m3Model = new()
    {
        ProfilePrefix = "ddeerG60m3Profile",
        DisplayName = "G60 m3",
        TypeCode = 602,
        TypeBytes = (11, 21, 1),
        KeyNames =G60m3Layout,
    };

    public static readonly KeyboardModel X60Model = new()
    {
        ProfilePrefix = "ddeerX60Profile",
        DisplayName = "X60",
        TypeCode = 603,
        TypeBytes = (11, 6, 5),
        KeyNames =X60Layout,
    };

    /// <summary>All 19 known DrunkDeer keyboard models, in catalog order.</summary>
    public static readonly IReadOnlyList<KeyboardModel> All =
    [
        A75ProModel,
        A75Model,
        A75UltraModel,
        A75MasterModel,
        A75UKModel,
        A75FRModel,
        A75DEModel,
        G75Model,
        G75JPModel,
        G65Model,
        G65LiteModel,
        G65m1Model,
        G65m2Model,
        G65m3Model,
        G60Model,
        G60m1Model,
        G60m2Model,
        G60m3Model,
        X60Model,
    ];

    // ---- Lookups ----

    public static KeyboardModel? FindByPid(int pid) =>
        All.FirstOrDefault(m => m.Pids.Contains(pid));

    public static KeyboardModel? FindByTypeCode(int code) =>
        All.FirstOrDefault(m => m.TypeCode == code);

    // Several A75 variants (UK, FR, DE) share TypeCode 751 and identical
    // TypeBytes (11,4,2). When that happens the caller needs to disambiguate
    // by PID or ProfilePrefix — see KeyboardLayoutResolver.
    public static IReadOnlyList<KeyboardModel> FindAllByTypeCode(int code) =>
        All.Where(m => m.TypeCode == code).ToList();

    public static KeyboardModel? FindByTypeBytes(byte b4, byte b5, byte b6) =>
        All.FirstOrDefault(m => m.TypeBytes == (b4, b5, b6));

    public static KeyboardModel? FindByProfilePrefix(string prefix) =>
        All.FirstOrDefault(m => m.ProfilePrefix == prefix);
}
